### ISSUE TITLE
Homework Feedback

### ISSUE THREAD

**Issue by arun-instructor** [heeeeee/fewd-hw5#1]
Hitomi,

Nice work! This looks great. A couple of quick suggestions:

- In your overlay-box class the transform is unnecessary. Simply specifying:

```css
.overlay-box {
  position:fixed;
  top:0;
  left:0;
  width:100%;
  height:100%;
}
```

will do. The box will stretch from the top left corner.

- Using hide/show to perform animations can be tricky since you're not guaranteed how it will look. It is better to perform these via CSS instead if this is the effect you're looking for. Also jQuery takes an optional callback function at the end, which since it is empty in your case, you can leave it off.
